import Car from "./Car";
import Colors from "./Colors";
import Directions from "./Directions";
import Doors from "./Doors";


const uno = new Car("Fiat", Colors.BLACK, 4);

uno.openTheDoor(Doors.DRIVER);
uno.closeTheDoor(Doors.DRIVER);
uno.turnOn();
uno.speedUp();
uno.speedUp();
uno.speedDown();
uno.turn(Directions.LEFT);
uno.speedUp();
uno.speedDown();
uno.turn(Directions.RIGHT);
uno.speedUp();
uno.speedDown();
uno.turn(Directions.RIGHT);
uno.speedUp();
uno.speedDown();
uno.stop();
uno.openTheDoor(Doors.BEHIND_RIDE);
uno.closeTheDoor(Doors.BEHIND_RIDE);
uno.speedUp();
uno.speedUp();
uno.speedDown();
uno.turn(Directions.RIGHT);
uno.speedUp();
uno.speedDown();
uno.turn(Directions.LEFT);
uno.speedUp();
uno.speedDown();
uno.turn(Directions.RIGHT);
uno.speedDown();
uno.stop();
uno.openTheDoor(Doors.BEHIND_RIDE);
uno.closeTheDoor(Doors.BEHIND_RIDE);
uno.speedUp();